[package]
name = "iradix"
version = "0.0.1"
edition = "2021"
repository = "https://github.com/al8n/iradix"
homepage = "https://github.com/al8n/iradix"
documentation = "https://docs.rs/iradix"
description = "A placeholder"
license = "MPL-2.0"
rust-version = "1.73"

[[bench]]
path = "benches/foo.rs"
name = "foo"
harness = false

[features]
default = ["std"]
std = ["bytes/default", "serde?/default", "lru/default"]
serde = ["dep:serde", "bytes/serde"]

[dependencies]
bytes = { version = "1", default-features = false }
lru = { version = "0.12", default-features = false }
indexsort = "0.1"
crossbeam-channel = { version = "0.5", optional = true }
crossbeam-epoch = "0.9"

serde = { version = "1.0", optional = true, default-features = false, features = ["derive"] }

[dev-dependencies]
criterion = "0.5"
tempfile = "3"
uuid = { version = "1", features = ["v4"] }

[target.'cfg(loom)'.dependencies]
loom = "0.7"

[profile.bench]
opt-level = 3
debug = false
codegen-units = 1
lto = 'thin'
incremental = false
debug-assertions = false
overflow-checks = false
rpath = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
